# GitHub Pages / Jekyll configuration
title: Your Project Name
description: Your project description

# Theme (optional - GitHub Pages supports these themes by default)
theme: minima

# Show directory listings
show_dir_listing: true

# Include normally hidden files in the build
include:
  - "README.md"
  - "LICENSE"

# Exclude files from being processed/shown
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown

# Permalinks
permalink: pretty
